### ISSUE TITLE
Problems trying to implement in Angular 5

### ISSUE THREAD

**Issue by moderniseobservatory** [ronikar/Leaflet.DistortableVideo#1]
I have finally written a very simple declaration file for this plugin that works with @types/leaflet.

However i do not know how to make sure that numeric/ jquery are being used. I have both downloaded in my project but when no video is appearing when i compile and try and view the webpage.

I know this is a js plugin and as such if you dont have an answer to help I understand, but any help would be greatly appreciated.

**Comment by ronikar** [comment]
Hi @Squrrli, 
I don't use Angular 5 at all, but if you want to be sure that numeric/ jquery are being used, try to add the scripts at index.html.

```html
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" type="text/javascript"></script>
<script src="./numeric.js" type="text/javascript"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>
<script src="./distortableVideoOverlay.js" type="text/javascript" /></script>
```
In Addition, you can read how to include and use jQuery in Angular CLI project on https://medium.com/@swarnakishore/how-to-include-and-use-jquery-in-angular-cli-project-592e0fe63176
Do the same for numeric.

I will try to create demo with Angular5, but it will take time....

**Comment by ronikar** [comment]
I created a simple [demo](https://github.com/ronikar/Leaflet.DistortableVideo/files/2084942/demo.zip) with AngularCLI. To run this demo, open cmd from the root directory and run `npm install`, then run `ng serve --open`.

### The changes you should do in your project:
At angular-cli.json (Angular5) or angular.json(Angular6) you should:
* Add scripts to the Angular CLI global scripts configuration.
```javascript
"scripts": [
              "./node_modules/jquery/dist/jquery.min.js",
              "./node_modules/numeric/numeric-1.2.6.js",
              "./node_modules/leaflet/dist/leaflet.js",
              "./node_modules/leaflet-distortable-video/dist/index.js"
            ]
``` 

* Add the Leaflet stylesheet to the Angular CLI global stylesheet configuration
```javascript
"styles": [
        "styles.css",
        "node_modules/leaflet/dist/leaflet.css"
      ]
```
