### ISSUE TITLE
rotate fork issue

### ISSUE THREAD

**Issue by mdellanave** [ronikar/Leaflet.DistortableVideo#6]
Hi ronikar, I'm writing here because it's the only place I found to contact you sorry.
Can you please open the issue panel on this project https://github.com/ronikar/Leaflet?

I found a problem on tooltips and popups when the map is rotated...
![image](https://user-images.githubusercontent.com/19222174/111160474-6ae85180-859a-11eb-95b8-d5bc31bf4a02.png)

Is there a chance to see a fix?

Thank you and have a nice day

**Comment by ronikar** [comment]
I opened the [issue panel](https://github.com/ronikar/Leaflet/issues).
Can you open your issue there?

**Comment by mdellanave** [comment]
Yes for sure, thank you man!
